dist: trusty
sudo: false
language: node_js
env:
  - CC=gcc-4.8
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
node_js:
  - "4"
compiler:
  - clang
  - gcc
